-- MySQL Script generated by MySQL Workbench
-- Tue Aug  8 16:12:02 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema sparkle_spa
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sparkle_spa
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sparkle_spa` DEFAULT CHARACTER SET utf8 ;
USE `sparkle_spa` ;

-- -----------------------------------------------------
-- Table `sparkle_spa`.`Shop`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sparkle_spa`.`Shop` (
  `SHOP.ID` INT NOT NULL AUTO_INCREMENT,
  `SHOP.UEN` INT NULL,
  `SHOP.CompanyName` VARCHAR(45) NULL,
  `SHOP.BusinessName` VARCHAR(50) NULL,
  `SHOP.ME.Lic` VARCHAR(45) NULL,
  `SHOP.ME.Exp` VARCHAR(45) NULL,
  `SHOP.CASE.Exp` VARCHAR(45) NULL,
  `SHOP.LIC.Owner.ID` VARCHAR(45) NULL,
  `SHOP.LIC.Owner.Name` VARCHAR(45) NULL,
  `SHOP.LIC.Owner.Mobile` VARCHAR(45) NULL,
  `SHOP.TotalRoom` VARCHAR(45) NULL,
  `SHOP.Start.Date` DATETIME NULL,
  `SHOP.End.Date` DATETIME NULL,
  `SHOP.Type` VARCHAR(45) NULL COMMENT '1=massage,2=nails,3=hair',
  `SHOP.AddressLine.1` VARCHAR(45) NULL,
  `SHOP.AddressLine.2` VARCHAR(45) NULL,
  `SHOP.GeneralManagerID` INT NULL,
  `SHOP.PaymentDefault` VARCHAR(45) NULL COMMENT '1= before service, 2 = after service',
  `SHOP.Logo` VARCHAR(45) NULL,
  PRIMARY KEY (`SHOP.ID`),
  UNIQUE INDEX `SHOP.ID_UNIQUE` (`SHOP.ID` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sparkle_spa`.`Person`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sparkle_spa`.`Person` (
  `PERSON.ID` INT NOT NULL AUTO_INCREMENT,
  `PERSON.UEN` VARCHAR(45) NULL,
  `PERSON.Name` VARCHAR(45) NULL,
  `PERSON.Nationality` VARCHAR(45) NULL,
  `PERSON.MobileNo` VARCHAR(45) NULL,
  `PERSON.Birthday` DATETIME NULL,
  `PERSON.Gender` VARCHAR(45) NULL,
  PRIMARY KEY (`PERSON.ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sparkle_spa`.`Staff`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sparkle_spa`.`Staff` (
  `STAFF.Acc.ID` INT NOT NULL AUTO_INCREMENT,
  `STAFF.UEN` VARCHAR(45) NULL,
  `STAFF.NICK` VARCHAR(45) NULL,
  `STAFF.Add` VARCHAR(45) NULL,
  `STAFF.PostalCode` VARCHAR(45) NULL,
  `STAFF.Type` INT NULL COMMENT '1 = manager, 2=therapist, 3=reception, 4 = service, 5=cleaner, 6=sale',
  `STAFF.Passport.Number` VARCHAR(45) NULL,
  `STAFF.Passport.Expiry` DATETIME NULL,
  `STAFF.Permit.Type` VARCHAR(45) NULL,
  `STAFF.Permit.Expiry` DATETIME NULL,
  `STAFF.SPF.Approval.Date` DATETIME NULL,
  `STAFF.SPF.Approval.Number` VARCHAR(45) NULL,
  `STAFF.Salary.Basic` VARCHAR(45) NULL,
  `STAFF.Salary.C1.Type` VARCHAR(45) NULL,
  `STAFF.Salary.C1.Value` VARCHAR(45) NULL,
  `STAFF.Salary.C2.Type` VARCHAR(45) NULL,
  `STAFF.Salary.C2.Threshold` VARCHAR(45) NULL,
  `STAFF.Salary.C2.Value` VARCHAR(45) NULL,
  `STAFF.PIN` VARCHAR(45) NULL,
  `STAFF.SHOP.ID` INT NULL,
  PRIMARY KEY (`STAFF.Acc.ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sparkle_spa`.`Customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sparkle_spa`.`Customer` (
  `CUS.Acc.ID` INT NOT NULL AUTO_INCREMENT,
  `CUS.NRIC` VARCHAR(45) NULL,
  `CUS.Name` VARCHAR(45) NULL,
  `CUS.Bday` DATETIME NULL,
  `CUS.Sex` VARCHAR(45) NULL,
  `CUS.Mobile` VARCHAR(45) NULL,
  `CUS.Email` VARCHAR(45) NULL,
  `CUS.Add` VARCHAR(45) NULL,
  `CUS.PostalCode` VARCHAR(45) NULL,
  `CUS.Nationality` VARCHAR(45) NULL,
  `CUS.First.Visit` DATETIME NULL,
  `CUS.Remarks` VARCHAR(45) NULL,
  `CUS.PIN` VARCHAR(45) NULL,
  `CUS.SHOP` VARCHAR(45) NULL,
  PRIMARY KEY (`CUS.Acc.ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sparkle_spa`.`MessageSession`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sparkle_spa`.`MessageSession` (
  `SXN.ID` INT NOT NULL AUTO_INCREMENT,
  `SXN.CUS.ID` INT NULL,
  `SXN.CASH` VARCHAR(45) NULL,
  `SXN.CC` VARCHAR(45) NULL,
  `SXN.NETS` VARCHAR(45) NULL,
  `SXN.Total.Discount` VARCHAR(45) NULL,
  `SXN.Incurred.Date` DATETIME NULL,
  `SXN.Last.Printed` VARCHAR(45) NULL,
  `SXN.Comments` VARCHAR(45) NULL,
  `SXN.STAFF.ID` INT NULL,
  `SXN.DEF` VARCHAR(45) NULL,
  `SXN.MAS.EnterRoom` INT NULL,
  `SXN.MAS.StartMsg` VARCHAR(45) NULL,
  `SXN.MAS.End` VARCHAR(45) NULL,
  `SXN.MAS.CleanUp` VARCHAR(45) NULL,
  PRIMARY KEY (`SXN.ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sparkle_spa`.`Transaction`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sparkle_spa`.`Transaction` (
  `TXN.ID` INT NOT NULL AUTO_INCREMENT,
  `TXN.SXN.ID` INT NULL,
  `TXN.SXN.ID.RANK` VARCHAR(45) NULL,
  `TXN.ITM.PACKAGE` VARCHAR(45) NULL,
  `TXN.ITM.PERCENTAGE.DISCOUNT` VARCHAR(45) NULL,
  `TXN.ITM.FLAT.DISCOUNT` VARCHAR(45) NULL,
  `TXN.ITM.TOTAL.DISCOUNT` VARCHAR(45) NULL,
  `TXN.ITM.PPP.ID` VARCHAR(45) NULL,
  `TXN.DATE.PAID` DATETIME NULL,
  `TXN.ROOM.ID` INT NULL,
  `TXN.STAFF.ID` INT NULL,
  `TXN.STAFF.Completed` VARCHAR(45) NULL,
  `TXN.Start` DATETIME NULL,
  `TXN.End` DATETIME NULL,
  `TXN.ITM.Type` VARCHAR(45) NULL,
  PRIMARY KEY (`TXN.ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sparkle_spa`.`Booking`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sparkle_spa`.`Booking` (
  `BKG.ID` INT NOT NULL AUTO_INCREMENT,
  `BKG.CUS.Acc.ID` INT NULL,
  `BKG.CUS.Name` VARCHAR(255) NULL,
  `BKG.CUS.Mobile` VARCHAR(45) NULL,
  `BKG.CUS.Email` VARCHAR(100) NULL,
  `BKG.Date` DATETIME NULL,
  `BKG.Time` VARCHAR(45) NULL,
  `BKG.MST` INT NULL,
  `BKG.Length` VARCHAR(45) NULL,
  `BKG.SHOP.ID` INT NULL,
  PRIMARY KEY (`BKG.ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sparkle_spa`.`PrePaidPackage`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sparkle_spa`.`PrePaidPackage` (
  `PPP.ID` INT NOT NULL AUTO_INCREMENT,
  `PPP.CUS.Acc.ID` INT NULL,
  `PPP.Start.Date` DATETIME NULL,
  `PPP.Expiry.Date` DATETIME NULL,
  `PPP.Topup.Value` VARCHAR(45) NULL,
  `PPP.Bonus.Value` VARCHAR(45) NULL,
  `PPP.Type` VARCHAR(45) NULL,
  `PPP.SHOP.ID` INT NULL,
  `PPP.Balance` VARCHAR(45) NULL,
  `PPP.PurchasePrice` VARCHAR(45) NULL,
  PRIMARY KEY (`PPP.ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sparkle_spa`.`MassageServiceItem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sparkle_spa`.`MassageServiceItem` (
  `ITM.ID` INT NOT NULL AUTO_INCREMENT,
  `ITM.Name.Eng` VARCHAR(45) NULL,
  `ITM.Name.Cn` VARCHAR(45) NULL,
  `ITM.Length` INT NULL,
  `ITM.FullPrice` VARCHAR(45) NULL,
  `ITM.PPP.Type1.Price` VARCHAR(45) NULL,
  `ITM.PPP.Type2.Price` VARCHAR(45) NULL,
  `ITM.PPP.Type3.Price` VARCHAR(45) NULL,
  `ITM.PPP.Type4.Price` VARCHAR(45) NULL,
  `ITM.PPP.Type5.Price` VARCHAR(45) NULL,
  `ITM.StartDate` DATETIME NULL,
  `ITM.EndDate` DATETIME NULL,
  `ITM.AutoApproval` VARCHAR(45) NULL,
  `ITM.Type` VARCHAR(45) NULL COMMENT '1=Massage,2=Addons,3=Goods.',
  PRIMARY KEY (`ITM.ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sparkle_spa`.`Resign`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sparkle_spa`.`Resign` (
  `RSN.ID` INT NOT NULL AUTO_INCREMENT,
  `RSN.STAFF.Acc.ID` INT NULL,
  `RSN.Action.Date` DATETIME NULL,
  `RSN.Submit.Date` DATETIME NULL,
  `RSN.Reason` VARCHAR(45) NULL,
  `RSN.Approval.Staff.ID` INT NULL,
  `RSN.Type` INT NULL COMMENT '1=Resign,2=Fire\n',
  PRIMARY KEY (`RSN.ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sparkle_spa`.`Promotion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sparkle_spa`.`Promotion` (
  `PRM.ID` INT NOT NULL AUTO_INCREMENT,
  `PRM.Code` VARCHAR(45) NULL,
  `PRM.SHOP.ID` INT NULL,
  `PRM.Start.Date` DATETIME NULL,
  `PRM.End.Date` DATETIME NULL,
  `PRM.Rate` VARCHAR(45) NULL,
  `PRM.Create.Date` DATETIME NULL,
  `PRM.Item.Type` VARCHAR(45) NULL,
  PRIMARY KEY (`PRM.ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sparkle_spa`.`WorkReport`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sparkle_spa`.`WorkReport` (
  `WRT.ID` INT NOT NULL AUTO_INCREMENT,
  `WRT.STAFF.Acc.ID` INT NULL,
  `WRT.Date` DATETIME NULL,
  `WRT.Content` VARCHAR(45) NULL,
  `WRT.Status` VARCHAR(45) NULL,
  PRIMARY KEY (`WRT.ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sparkle_spa`.`Room`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sparkle_spa`.`Room` (
  `ROOM.ID` INT NOT NULL AUTO_INCREMENT,
  `ROOM.Number` INT NULL,
  `ROOM.Name` VARCHAR(45) NULL,
  `ROOM.SHOP.ID` INT NULL,
  PRIMARY KEY (`ROOM.ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sparkle_spa`.`Offday`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sparkle_spa`.`Offday` (
  `OFD.ID` INT NOT NULL AUTO_INCREMENT,
  `OFD.OffDate` DATETIME NULL,
  `OFD.Reason` VARCHAR(45) NULL,
  `OFD.STAFF.Acc.ID` INT NULL,
  `OFD.Create.Date` DATETIME NULL,
  `OFD.Status` INT NULL,
  PRIMARY KEY (`OFD.ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sparkle_spa`.`Admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sparkle_spa`.`Admin` (
  `ADMIN.ID` INT NOT NULL AUTO_INCREMENT,
  `ADMIN.Email` VARCHAR(100) NULL,
  `ADMIN.Username` VARCHAR(100) NULL,
  `ADMIN.Password` VARCHAR(255) NULL,
  PRIMARY KEY (`ADMIN.ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sparkle_spa`.`Owner`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sparkle_spa`.`Owner` (
  `OWNER.ID` INT NOT NULL AUTO_INCREMENT,
  `OWNER.Email` VARCHAR(45) NULL,
  `OWNER.Password` VARCHAR(45) NULL,
  `OWNER.SHOP.ID` INT NULL,
  PRIMARY KEY (`OWNER.ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sparkle_spa`.`ActionHistory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sparkle_spa`.`ActionHistory` (
  `ATH.ID` INT NOT NULL AUTO_INCREMENT,
  `ATH.STAFF.Acc.ID` INT NULL,
  `ATH.Content` VARCHAR(45) NULL,
  `ATH.Date` DATETIME NULL,
  PRIMARY KEY (`ATH.ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sparkle_spa`.`LoginInfo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sparkle_spa`.`LoginInfo` (
  `LGI.ID` INT NOT NULL AUTO_INCREMENT,
  `LGI.Name` VARCHAR(45) NULL,
  `LGI.NumberID` VARCHAR(50) NULL,
  `LGI.Mobile` VARCHAR(45) NULL,
  `LGI.Email` VARCHAR(45) NULL,
  `LGI.Role` VARCHAR(45) NULL,
  `LGI.InfoID` VARCHAR(45) NULL,
  `LGI.Password` VARCHAR(45) NULL,
  PRIMARY KEY (`LGI.ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sparkle_spa`.`HolderInfo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sparkle_spa`.`HolderInfo` (
  `HDI.ID` INT NOT NULL AUTO_INCREMENT,
  `HDI.Owner.ID` INT NULL,
  `HDI.SHOP.ID` INT NULL,
  `HDI.Percentage` FLOAT NULL,
  PRIMARY KEY (`HDI.ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sparkle_spa`.`ShopManager`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sparkle_spa`.`ShopManager` (
  `SM.ID` INT NOT NULL AUTO_INCREMENT,
  `SM.SHOP.ID` INT NULL,
  `SM.ManagerID` INT NULL,
  PRIMARY KEY (`SM.ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sparkle_spa`.`ShopOpeningHour`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sparkle_spa`.`ShopOpeningHour` (
  `SOH.ID` INT NOT NULL AUTO_INCREMENT,
  `SOH.SHOP.iD` INT NULL,
  `SOH.DayInWeek` INT NULL COMMENT '1 to 7.. Start from Sunday',
  `SOH.OpenTime` VARCHAR(45) NULL,
  `SOH.CloseTime` VARCHAR(45) NULL,
  PRIMARY KEY (`SOH.ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sparkle_spa`.`CustomerVisit`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sparkle_spa`.`CustomerVisit` (
  `CMV.ID` INT NOT NULL AUTO_INCREMENT,
  `CMV.CUS.Acc.ID` INT NULL,
  `CMV.SHOP.ID` INT NULL,
  `CMV.VisitDate` DATETIME NULL,
  PRIMARY KEY (`CMV.ID`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
