-- MySQL Script generated by MySQL Workbench
-- Tue Aug 15 16:25:12 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema sparkle_spa_2
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sparkle_spa_2
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sparkle_spa_2` DEFAULT CHARACTER SET utf8 ;
USE `sparkle_spa_2` ;

-- -----------------------------------------------------
-- Table `sparkle_spa_2`.`Shop`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sparkle_spa_2`.`Shop` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `UEN` INT NULL,
  `company_name` VARCHAR(45) NULL,
  `business_name` VARCHAR(50) NULL,
  `ME_Lic` VARCHAR(45) NULL,
  `ME_Exp` VARCHAR(45) NULL,
  `CASE_Exp` VARCHAR(45) NULL,
  `LIC_OwnerID` VARCHAR(45) NULL,
  `LIC_Owner_Name` VARCHAR(45) NULL,
  `LIC_Owner_Mobile` VARCHAR(45) NULL,
  `total_room` VARCHAR(45) NULL,
  `start_date` DATETIME NULL,
  `end_date` DATETIME NULL,
  `type` VARCHAR(45) NULL COMMENT '1=massage,2=nails,3=hair',
  `address_line1` VARCHAR(45) NULL,
  `address_line2` VARCHAR(45) NULL,
  `general_managerID` INT NULL,
  `payment_default` VARCHAR(45) NULL COMMENT '1= before service, 2 = after service',
  `logo` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `SHOP.ID_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sparkle_spa_2`.`Person`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sparkle_spa_2`.`Person` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `UEN` VARCHAR(45) NULL,
  `name` VARCHAR(45) NULL,
  `nationality` VARCHAR(45) NULL,
  `mobile_no` VARCHAR(45) NULL,
  `birthday` DATETIME NULL,
  `gender` VARCHAR(45) NULL,
  `role` VARCHAR(45) NULL COMMENT '1=owner,2=admin, 3=staff\n',
  `email` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sparkle_spa_2`.`Staff`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sparkle_spa_2`.`Staff` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `UEN` VARCHAR(45) NULL,
  `NICK` VARCHAR(45) NULL,
  `address` VARCHAR(45) NULL,
  `postal_code` VARCHAR(45) NULL,
  `type` INT NULL COMMENT '1 = manager, 2=therapist, 3=reception, 4 = service, 5=cleaner, 6=sale',
  `passport_number` VARCHAR(45) NULL,
  `passport_expiry` DATETIME NULL,
  `permit_type` VARCHAR(45) NULL,
  `permit_expiry` DATETIME NULL,
  `SPF_approval_date` DATETIME NULL,
  `SPF_approval_number` VARCHAR(45) NULL,
  `salary_basic` VARCHAR(45) NULL,
  `salary_C1Type` VARCHAR(45) NULL,
  `salary_C1Value` VARCHAR(45) NULL,
  `salary_C2Type` VARCHAR(45) NULL,
  `salary_C2Threshold` VARCHAR(45) NULL,
  `salary_C2Value` VARCHAR(45) NULL,
  `PIN` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sparkle_spa_2`.`Customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sparkle_spa_2`.`Customer` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `NRIC` VARCHAR(45) NULL,
  `name` VARCHAR(45) NULL,
  `birthday` DATETIME NULL,
  `sex` VARCHAR(45) NULL,
  `mobile` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `add` VARCHAR(45) NULL,
  `postal_code` VARCHAR(45) NULL,
  `nationality` VARCHAR(45) NULL,
  `first_visit` DATETIME NULL,
  `remarks` VARCHAR(45) NULL,
  `PIN` VARCHAR(45) NULL,
  `SHOP` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sparkle_spa_2`.`MessageSession`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sparkle_spa_2`.`MessageSession` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `CUS_ID` INT NULL,
  `cash` VARCHAR(45) NULL,
  `CC` VARCHAR(45) NULL,
  `NETS` VARCHAR(45) NULL,
  `total_discount` VARCHAR(45) NULL,
  `incurred_date` DATETIME NULL,
  `last_printed` VARCHAR(45) NULL,
  `comments` VARCHAR(45) NULL,
  `STAFF_ID` INT NULL,
  `DEF` VARCHAR(45) NULL,
  `MAS_EnterRoom` INT NULL,
  `MAS_StartMsg` VARCHAR(45) NULL,
  `MAS_End` VARCHAR(45) NULL,
  `MAS_CleanUp` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sparkle_spa_2`.`Transaction`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sparkle_spa_2`.`Transaction` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `SXN_ID` INT NULL,
  `SXN_ID_RANK` VARCHAR(45) NULL,
  `ITM_PACKAGE` VARCHAR(45) NULL,
  `ITM_PERCENTAGE_DISCOUNT` VARCHAR(45) NULL,
  `ITM_FLAT_DISCOUNT` VARCHAR(45) NULL,
  `ITM_TOTAL_DISCOUNT` VARCHAR(45) NULL,
  `ITM_PPP_ID` VARCHAR(45) NULL,
  `DATE_PAID` DATETIME NULL,
  `ROOM_ID` INT NULL,
  `STAFF_ID` INT NULL,
  `STAFF_Completed` VARCHAR(45) NULL,
  `start` DATETIME NULL,
  `end` DATETIME NULL,
  `ITM_Type` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sparkle_spa_2`.`Booking`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sparkle_spa_2`.`Booking` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `CUS_AccID` INT NULL,
  `CUS_Name` VARCHAR(255) NULL,
  `CUS_Mobile` VARCHAR(45) NULL,
  `CUS_Email` VARCHAR(100) NULL,
  `date` DATETIME NULL,
  `time` VARCHAR(45) NULL,
  `mst` INT NULL,
  `lenght` VARCHAR(45) NULL,
  `SHOP_ID` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sparkle_spa_2`.`PrePaidPackage`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sparkle_spa_2`.`PrePaidPackage` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `CUS_AccID` INT NULL,
  `start_date` DATETIME NULL,
  `expiry_date` DATETIME NULL,
  `topup_value` VARCHAR(45) NULL,
  `bonus_value` VARCHAR(45) NULL,
  `type` VARCHAR(45) NULL,
  `shop_id` INT NULL,
  `balance` VARCHAR(45) NULL,
  `purchase_price` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sparkle_spa_2`.`MassageServiceItem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sparkle_spa_2`.`MassageServiceItem` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name_eng` VARCHAR(45) NULL,
  `name_cn` VARCHAR(45) NULL,
  `length` INT NULL,
  `full_price` VARCHAR(45) NULL,
  `PPP_Type1_Price` VARCHAR(45) NULL,
  `PPP_Type2_Price` VARCHAR(45) NULL,
  `PPP_Type3_Price` VARCHAR(45) NULL,
  `PPP_Type4_Price` VARCHAR(45) NULL,
  `PPP_Type5_Price` VARCHAR(45) NULL,
  `start_date` DATETIME NULL,
  `end_date` DATETIME NULL,
  `auto_approval` VARCHAR(45) NULL,
  `ITM.Type` VARCHAR(45) NULL COMMENT '1=Massage,2=Addons,3=Goods.',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sparkle_spa_2`.`Resign`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sparkle_spa_2`.`Resign` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `STAFF_AccID` INT NULL,
  `action_date` DATETIME NULL,
  `submit_date` DATETIME NULL,
  `reason` VARCHAR(45) NULL,
  `approval_StaffID` INT NULL,
  `type` INT NULL COMMENT '1=Resign,2=Fire\n',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sparkle_spa_2`.`Promotion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sparkle_spa_2`.`Promotion` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(45) NULL,
  `shop_id` INT NULL,
  `start_date` DATETIME NULL,
  `end_date` DATETIME NULL,
  `rate` VARCHAR(45) NULL,
  `create_date` DATETIME NULL,
  `item_type` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sparkle_spa_2`.`WorkReport`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sparkle_spa_2`.`WorkReport` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `STAFF_AccID` INT NULL,
  `date` DATETIME NULL,
  `content` VARCHAR(45) NULL,
  `status` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sparkle_spa_2`.`Room`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sparkle_spa_2`.`Room` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `number` INT NULL,
  `name` VARCHAR(45) NULL,
  `shop_id` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sparkle_spa_2`.`Offday`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sparkle_spa_2`.`Offday` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `off_date` DATETIME NULL,
  `reason` VARCHAR(45) NULL,
  `STAFF_AccID` INT NULL,
  `create_date` DATETIME NULL,
  `status` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sparkle_spa_2`.`SuperAdmin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sparkle_spa_2`.`SuperAdmin` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(100) NULL,
  `username` VARCHAR(100) NULL,
  `password` VARCHAR(255) NULL,
  `create_date` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sparkle_spa_2`.`ActionHistory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sparkle_spa_2`.`ActionHistory` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `STAFF_AccID` INT NULL,
  `content` VARCHAR(45) NULL,
  `create_date` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sparkle_spa_2`.`LoginInfo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sparkle_spa_2`.`LoginInfo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NULL,
  `last_name` VARCHAR(45) NULL,
  `number_id` VARCHAR(50) NULL,
  `mobile` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `role` VARCHAR(45) NULL,
  `info_id` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sparkle_spa_2`.`HolderInfo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sparkle_spa_2`.`HolderInfo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `owner_id` INT NULL,
  `shop_id` INT NULL,
  `percentage` FLOAT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sparkle_spa_2`.`ShopOpeningHour`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sparkle_spa_2`.`ShopOpeningHour` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `shop_id` INT NULL,
  `day_in_week` INT NULL COMMENT '1 to 7.. Start from Sunday',
  `open_time` VARCHAR(45) NULL,
  `close_time` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sparkle_spa_2`.`CustomerVisit`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sparkle_spa_2`.`CustomerVisit` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `CUS_AccID` INT NULL,
  `shop_id` INT NULL,
  `visit_date` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sparkle_spa_2`.`ShopStaff`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sparkle_spa_2`.`ShopStaff` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `shop_id` INT NULL,
  `staff_id` INT NULL,
  `role` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
